config/routes.rb
Rails.application.routes.draw do

  resources :questions do
    member do
      post 'answer'
    end
  end

  root 'questions#randomize'

end

app/models/answer.rb
class Answer < ActiveRecord::Base

  belongs_to :question

end

app/models/question.rb
class Question < ActiveRecord::Base
  has_many :answers, dependent: :destroy do
    def correct
      where(correct: true).first
    end
  end

  def answer
    answers.correct && answers.correct.text
  end

  def answer=(ans_text)
    answers << Answer.create(text: ans_text, correct: true)
  end

  def wrongs
    answers && answers.where(correct:false).map(&:text).join(',')
  end

  def wrongs=(ans_text)
    puts 'AAAAAAAAAAAAAAAAAAAAA'
    puts ans_text
    ans_text.split(',').each do |ans|
      puts ans
      answers << Answer.create(text: ans.strip, correct: false)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  before_action :get_question, only: [:show, :edit, :update, :destroy, :answer]

  # GET /questions
  def index
    @questions = Question.all
  end

  # GET /questions/1
  def show
  end

  # GET /questions/new
  def new
    @question = Question.new
  end

  # GET /questions/1/edit
  def edit
  end

  # POST /questions
  def create
    @question = Question.new(question_params)
    @question.save
    redirect_to question_path(@question)
  end

  # PATCH/PUT /questions/1
  def update
    redirect_to question_path(@question)
  end

  # DELETE /questions/1
  def destroy
    @question.destroy
    redirect_to '/'
  end

  def randomize
    @question = Question.all.sample
    redirect_to question_path(@question)
  end

  def answer
    if params[:Answer] == @question.answer
      flash[:notice] = 'Correct'
    else
      flash[:notice] = 'Wrong Answer'
    end
    redirect_to action: :randomize
  end

  private
  def get_question
    @question = Question.find(params[:id])
  end

  def question_params
    params.require(:question).permit(:text, :answer, :wrongs)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>QuestionChallenger</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/questions/_form.html.haml
= form_for @question do |f|
  - if @question.errors.any?
    #error_explanation
      %h2= "#{pluralize(@question.errors.count, "error")} prohibited this question from being saved:"
      %ul
        - @question.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :text
    = f.text_area :text
    %br
    = f.label :answer
    = f.text_field :answer
    %br
    optional (fill in if multiple choice, comma-seperated):
    %br
    = f.label 'wrong answers'
    = f.text_field :wrongs
  .actions
    = f.submit 'Save'

app/views/questions/edit.html.haml
%h1 Editing question

= render 'form'

= link_to 'Show', @question
\|
= link_to 'Back', questions_path

app/views/questions/index.html.haml
%h1 Listing questions

%table
  %tr
    %th Text
    %th
    %th
    %th

  - @questions.each do |question|
    %tr
      %td= question.text
      %td= link_to 'Show', question
      %td= link_to 'Edit', edit_question_path(question)
      %td= link_to 'Destroy', question, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Question', new_question_path

app/views/questions/new.html.haml
%h1 New question

= render 'form'

= link_to 'Back', questions_path

app/views/questions/show.html.haml
%p#notice= notice

%p
  %b Text:
  = @question.text

= link_to 'Edit', edit_question_path(@question)
\|
= link_to 'Back', questions_path

- if @question.answers.count > 1
  - @question.answers.each do |answer|
    = form_tag answer_question_path do
      = hidden_field_tag('Answer', answer.text)
      = button_tag(answer.text)
- else
  = form_tag answer_question_path do
    = text_field_tag 'Answer'
    = submit_tag 'Submit'